spring:
    profiles:
        active:
        -dev
        
---
spring:
    profiles: dev
    application:
        name: platform-config-dev

---
spring:
    profiles: test
    application:
        name:platform-config-test
        
        
        